version:
  name: velociraptor
  version: 0.7.0
  commit: ac56954c
  build_time: "2023-08-28T02:38:17Z"
  install_time: 1694252753
  compiler: go1.19.12
Client:
  server_urls:
  - https://18.132.171.49:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRAPLPNe+9PxfgJu7AlFA4ZpkwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIzMDkwOTA5NDYwNVoXDTMz
    MDkwNjA5NDYwNVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4wJSBsqZWZT2Fm/+0QhUQ9EDD35E7pl9
    NQxyUgXSItfQQ+u7l2Ikq+SRqJdIs6KGJTIZ6FRQS98/eR6eyg4morxwdjBibA9l
    YCBuc+62di4y1KtDLW0+FV9oYnFTDJ/T8XFKPn77delF3+rAppKxzV0Q8EZ6vlnC
    jeb/oVIpiDRHllxbxztT7+ANmtIdP2VQ4fmbDU3QkiLMN9gwscyHAKOSbjJFbzAl
    cpp8nBT87xylxiXZH+kHl6waYT6w5YVStsg26yyq7GXv0BtvihlyMRFrhjenMPYQ
    AzE7Fl2h/5tY8CBSCRBLNqT7eTE3xES9+myP00yjrYD7sQlybm9NzQIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUJ1W0DFFW0rWv7wcNd+uTvOkW
    b58wKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBADhO5jP/5S7ShGMtFSwkpONWXNbN/JShGkBQEtSOAMJT
    ZZ+s0hD6qChDlfTUW7H0sNaJM1n+F0lCiu+cMhPPIGP81O6UShQh/QdVkup2R/ts
    URZUnEjnOV/X/KlDgXkd8G+IofahueTADTJA8q8lHtQ6NqLu8Vew6Kxcjk6ahoW/
    DCZD5g96tREC182aNTRkhNJ212Ut7id804qSRivQ8IB6U6OW626f1MXnVHnB9WdL
    nDMGPeh2dcbU+jUjFYTNKRNRVNGjiTRTPoKKgrM1PTirjci+ipdHayEXS6XSzm7M
    4B754lF4V0xPOok1wOIoh3U109sq4KysTCoR2HS6sZw=
    -----END CERTIFICATE-----
  nonce: URESp2tCS58=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.0
    commit: ac56954c
    build_time: "2023-08-28T02:38:17Z"
    install_time: 1694252753
    compiler: go1.19.12
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
